export type PhotoMarqueeRowName = "top" | "middle" | "bottom";

export type PhotoMarqueePhoto = {
    src: `/marquee/${string}`;
    objectPosition?: string;
};

export const topPhotos: readonly PhotoMarqueePhoto[] = [
    {src: "/marquee/top-001.webp"},
    {src: "/marquee/top-002.webp"},
    {src: "/marquee/top-003.webp"},
    {src: "/marquee/top-004.webp"},
    {src: "/marquee/top-005.webp"},
    {src: "/marquee/top-006.webp"},
    {src: "/marquee/top-007.webp"},
    {src: "/marquee/top-008.webp"},
    {src: "/marquee/top-009.webp"},
    {src: "/marquee/top-010.webp"},
    {src: "/marquee/top-011.webp"},
    {src: "/marquee/top-012.webp"},
    {src: "/marquee/top-013.webp"},
    {src: "/marquee/top-014.webp"},
    {src: "/marquee/top-015.webp"},
    {src: "/marquee/top-016.webp"},
    {src: "/marquee/top-017.webp"},
    {src: "/marquee/top-018.webp"},
    {src: "/marquee/top-019.webp"},
    {src: "/marquee/top-020.webp"},
    {src: "/marquee/top-021.webp"},
    {src: "/marquee/top-022.webp"},
    {src: "/marquee/top-023.webp"},
    {src: "/marquee/top-024.webp"},
    {src: "/marquee/top-025.webp"},
    {src: "/marquee/top-026.webp"},
    {src: "/marquee/top-027.webp"},
    {src: "/marquee/top-028.webp"},
    {src: "/marquee/top-029.webp"},
    {src: "/marquee/top-030.webp"},
    {src: "/marquee/top-031.webp"},
    {src: "/marquee/top-032.webp"},
    {src: "/marquee/top-033.webp"},
];

export const middlePhotos: readonly PhotoMarqueePhoto[] = [
    {src: "/marquee/middle-001.webp"},
    {src: "/marquee/middle-002.webp"},
    {src: "/marquee/middle-003.webp"},
    {src: "/marquee/middle-004.webp"},
    {src: "/marquee/middle-005.webp"},
    {src: "/marquee/middle-006.webp"},
    {src: "/marquee/middle-007.webp"},
    {src: "/marquee/middle-008.webp"},
    {src: "/marquee/middle-009.webp"},
    {src: "/marquee/middle-010.webp"},
    {src: "/marquee/middle-011.webp"},
    {src: "/marquee/middle-012.webp"},
    {src: "/marquee/middle-013.webp"},
    {src: "/marquee/middle-014.webp"},
    {src: "/marquee/middle-015.webp"},
    {src: "/marquee/middle-016.webp"},
    {src: "/marquee/middle-017.webp"},
    {src: "/marquee/middle-018.webp"},
    {src: "/marquee/middle-019.webp"},
    {src: "/marquee/middle-020.webp"},
    {src: "/marquee/middle-021.webp"},
    {src: "/marquee/middle-022.webp"},
    {src: "/marquee/middle-023.webp"},
    {src: "/marquee/middle-024.webp"},
    {src: "/marquee/middle-025.webp"},
    {src: "/marquee/middle-026.webp"},
    {src: "/marquee/middle-027.webp"},
    {src: "/marquee/middle-028.webp"},
    {src: "/marquee/middle-029.webp"},
    {src: "/marquee/middle-030.webp"},
    {src: "/marquee/middle-031.webp"},
    {src: "/marquee/middle-032.webp"},
];

export const bottomPhotos: readonly PhotoMarqueePhoto[] = [
    {src: "/marquee/bottom-001.webp"},
    {src: "/marquee/bottom-002.webp"},
    {src: "/marquee/bottom-003.webp"},
    {src: "/marquee/bottom-004.webp"},
    {src: "/marquee/bottom-005.webp"},
    {src: "/marquee/bottom-006.webp"},
    {src: "/marquee/bottom-007.webp"},
    {src: "/marquee/bottom-008.webp"},
    {src: "/marquee/bottom-009.webp"},
    {src: "/marquee/bottom-010.webp"},
    {src: "/marquee/bottom-011.webp"},
    {src: "/marquee/bottom-012.webp"},
    {src: "/marquee/bottom-013.webp"},
    {src: "/marquee/bottom-014.webp"},
    {src: "/marquee/bottom-015.webp"},
    {src: "/marquee/bottom-016.webp"},
    {src: "/marquee/bottom-017.webp"},
    {src: "/marquee/bottom-018.webp"},
    {src: "/marquee/bottom-019.webp"},
    {src: "/marquee/bottom-020.webp"},
    {src: "/marquee/bottom-021.webp"},
    {src: "/marquee/bottom-022.webp"},
    {src: "/marquee/bottom-023.webp"},
    {src: "/marquee/bottom-024.webp"},
    {src: "/marquee/bottom-025.webp"},
    {src: "/marquee/bottom-026.webp"},
    {src: "/marquee/bottom-027.webp"},
    {src: "/marquee/bottom-028.webp"},
    {src: "/marquee/bottom-029.webp"},
    {src: "/marquee/bottom-030.webp"},
    {src: "/marquee/bottom-031.webp"},
    {src: "/marquee/bottom-032.webp"},
];
